before_install:
  - sudo apt-get install -y libhunspell-1.3-0 || apt-get install -y libhunspell-1.2-0 
  - sudo apt-get install -y hunspell-en-us
  - sudo apt-get install -y hunspell-de-de
language: ruby
rvm:
  - 2.2.0
env:
  CODECLIMATE_REPO_TOKEN=891f2b22f36f5d18a68d846c5ea45276885d0d1442a681d36db435a8a97a15b3
